### ISSUE TITLE
Extension Doesn't Honor Proxy Cred Injection

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/gitguardian-vscode#37]
## Environment

- VSCode extension version: 0.3.0
- VSCode version: 1.94.2
- Operating system (Linux, macOS, Windows): macOS
- Operating system version: 14.7

## Describe the bug

We have what may be considered an unsupported architecture, so feel free to close as such...

Our GGShield/GitGuardian users do not have accounts directly within the GG Dashboard.  Instead, we inject the API authentication header using a proxy.  When using the GGShield client directly our developer set two environment variables:

```
GITGUARDIAN_API_KEY=unset
GITGUARDIAN_INSTANCE=https://gg-api-auth.our.internal.domain
```

With these variables set users are not required to authenticate.

I've replicated this setup in the VSCode extension settings ("Api Url" and "Api Key") and restarted VSCode, but the extension is still prompting for login.

I've also tried to specify the GGShield path to my (Python package) installation of GGShield without change.

**Comment by mathieubellon** [comment]
Hello @rgajason,
I think we can update our design to suit your case - expect an update in the coming days

**Comment by mathieubellon** [comment]
Hello @rgajason 
Can you tell me if the recent v0.4.0 release help to solve your problem ?

**Comment by rgajason** [comment]
Hi @mathieubellon .  I upgraded to 0.4.0 on VSCode 1.95.1 and it is still prompting me to authenitcate (to link my IDE with my account).

**Comment by mathieubellon** [comment]
Hi @rgajason - strange, I'll get back to you shortly

**Comment by rgajason** [comment]
Hi @mathieubellon.  I upgraded to 0.5.0, but I'm experiencing the same behavior (message to link IDE with account).  Here's a recap of my current setup:

VSCode settings for GG have "Api Url" set to internal proxy (`https://gg-api-auth.internal.dom`) and "Allow Self Signed" is *not* checked (we use an internal CA but it is in the OS trust store).  No other GG settings are visible.

For the CLI we normally have to set a second variable (`GITGUARDIAN_API_KEY`) to a dummy value to "trick" it.  I've tried a couple variations of replicating that setup:

- Setting via `launch.json`
- Setting via `.zshrc` and launching in terminal

Our proxy adds an HTTP header with the authentication token, if that matters.

I appreciate the work.  Again, I understand if this use case is not supported.

**Comment by mathieubellon** [comment]
Hello @rgajason 

Sorry for the delay and issue not being fixed, it is a complex one
Officially let's say we cannot support this use case yet (as it is also complex to reproduce on our side)
Off the record I will try again with the team, later in Q1,  to push again and try to crack this problem.

I close this ticket issue for now and re open a channel with your CSM if we make progress on this
