### ISSUE TITLE
Test creation sync integration

### ISSUE THREAD

**Issue by mathieubellon** [GitGuardian/gitguardian-vscode#49]
## Environment

- VSCode extension version:
- VSCode version:
- Operating system (Linux, macOS, Windows):
- Operating system version:

## Describe the bug

Steps to reproduce:

1. Setup steps required to reproduce the issue
2. Run command `ggshield scan something`
3. …

Actual result:

Expected result:

If applicable, add logs or screenshots to help explain your problem.

**Comment by mathieubellon** [comment]
test comment back to GH

**Comment by kda-jt** [comment]
blabla
